### ISSUE TITLE
Minimum supported iOS version

### ISSUE THREAD

**Issue by ravilich86** [divadretlaw/CustomAlert#23]
### Description
The library currently has a dependency on WindowKit, which is causing compatibility issues with iOS versions prior to iOS 17.

### Problem Details
- WindowKit includes an extension for `MainActor`
- This extension uses the method `try MainActor.assumeIsolated()`
- The `assumeIsolated()` method is only available from iOS 17 onwards

Is iOS 17+ the intended minimum supported version for this library?

Thank you for your attention to this issue.

**Comment by divadretlaw** [comment]
> Is iOS 17+ the intended minimum supported version for this library?

No, iOS 14 is still the intended minimum.

> The `assumeIsolated()` method is only available from iOS 17 onwards

Technically [`MainActor.assumeIsolated(_:file:line:)`](https://developer.apple.com/documentation/swift/mainactor/assumeisolated(_:file:line:)-swift.type.method) has been back ported to iOS 13.

But that being said, I think that is only the case using Swift 5.10+ and not the currently specified minimum of 5.9.

## Possible fixes

Do you need Swift 5.9 support? 

If yes, I will re-add a variant I dropped because I wrongly thought it was generally back ported, not realizing it was only for Swift 5.10.

If not I will probably just increase the minimum required Swift version to 5.10

**Comment by ravilich86** [comment]
Thank you for your quick and detailed response! I really appreciate your attention to this issue.

Regarding your questions and points:

1. My current setup:
   - I'm using macOS Big Sur
   - My Xcode version is 15.2, which only supports Swift 5.9
   - With this setup, I can still build applications for iOS 17

2. Swift version support:
   Given my current environment, support for Swift 5.9 would be incredibly helpful. While I'm planning to update my machine in the near future, having Swift 5.9 support would allow me to use your library immediately without any compatibility issues.

**Comment by divadretlaw** [comment]
Sounds perfectly reasonable, I updated CustomAlert (and its dependencies) and tagged version `3.8.0`

Should now work with Xcode 15.0+, as advertised with support for Swift 5.9

If it still doesn't work, please let me know, also thank you for noticing this issue 😺
